CREATE TABLE IF NOT EXISTS widgets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    weight INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Name constraints (5...250)
ALTER TABLE widgets
ADD CONSTRAINT widget_name_length_check 
CHECK (LENGTH(name) BETWEEN 5 AND 250);
